### ISSUE TITLE
implement mouse icon change detector?

### ISSUE THREAD

**Issue by pessimo** [olesgeras/AutoFish#5]
this is a good bot program. 
Here, I present another method, and maybe we can discuss if it's good.

this method is detecting mouse icon changes when the mouse scan line by line across a certain area of the screen.
when the mouse icon change to a hook shape, it means the mouse touches the float. and the scan shall stop immediately, and move downwards a certain distance until it changes back to normal shape. 

when you get the fish, the float will move downwards a little and touches the mouse, then the mouse icon will change to a hook shape again, and it's time to click float to catch the fish.

the pros of this method are:
1 it does not rely on graphic driver
2 it does not rely on lighting and will not be influenced by environmental color
3 it will not be influenced by others fishing near you

the only con of this method is you need a lot of clipping and comparing work

**Comment by olesgeras** [comment]
Interesting idea, the problem is that a mouse movement generally takes a lot of resources and even without delay it would take a lot of time to pass even 10 rows (if our fishing zone is 500px wide the mouse should pass 500x10 = 5000 positions). Even if we made it jump over some pixels to match only the size of the bobber (which is relative to the camera position, and we would need to take that into account too), it would be too inefficient unfortunately. We should also consider that movements of our mouse might be tracked and the method would reveal that we are using software rather quickly. 

Another problem is that a cursor doesn't exist in the same layer of pixels as the game, it's generated over it, so we won't be able to capture any information about it (we can get around this by using a hint window that appears in the right bottom of the screen when the mouse is over the bobber, but still...).  

Considering the problem with other players, in my opinion it's not so important, the world of the World of Warcraft is quite huge and it's not difficult to find another place. :)
