### ISSUE TITLE
increase attempt times 

### ISSUE THREAD

**Issue by chouhsin** [olesgeras/AutoFish#6]
hello olesgeras!
can you increase attempt times from 3 to 10,or to customs?  it is so easy to stop fishing after 3 times of attempts

**Comment by olesgeras** [comment]
Will add the option to the next update. But the thing is, if the bot can't find a bobber after 3 attempts it can indicate to one of these issues:

1. Place/direction isn't well enough.
2. The bad weather appeared. 
3. Bobber is outside the fishing zone.
4. The bobber landed 3 times in one place. 

Could you analyze what is the issue in your case so that I understand why it occurs?

**Comment by olesgeras** [comment]
Added the option, you can find it in the "Advanced settings".
